name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env: 
      HOST: localhost
      DBPORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
      SSL_MODE: disable
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest', 'ubuntu-22.04']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      
      - name: Build-DB
        run: docker compose build
      
      - name: Create-DB
        run: docker compose up -d

      - name: Load Test Env
        run: |
          echo "HOST=${{ env.HOST }}" >> .env.test
          echo "USER=${{ env.USER }}" >> .env.test
          echo "PASSWORD=${{ env.PASSWORD }}" >> .env.test
          echo "DBNAME=${{ env.DBNAME }}" >> .env.test
          echo "DBPORT=${{ env.DBPORT }}" >> .env.test
          echo "SSL_MODE=${{ env.SSL_MODE }}" >> .env.test

      - name: Test
        run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: go build -v main.go

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-main-golang
          path: main

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

  Deploy_EC2:
    needs: build
    uses: ./.github/workflows/EC2.yml
    secrets: inherit
